version: '2'

services:
  deployment:
    image: node:latest
    environment:
      - VIRTUAL_HOST=deployment.dpstudios.es
      - NODE_ENV=development
    volumes:
      - ./app:/app
    working_dir: /app
    command: npm start
    ports:
      - "3000"
